name: altoke_common
description: A set of common elements used across projects.
version: 0.0.1+1
publish_to: none
#x-remove-start#
resolution: workspace
#remove-end#

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  #{{#use_dart_mappable}}x#
  dart_mappable: ^4.6.1
  #x{{/use_dart_mappable}}x#
  #x{{#use_equatable}}x#
  equatable: ^2.0.8
  #x{{/use_equatable}}x#
  #x{{#use_freezed}}x#
  freezed_annotation: ^3.1.0
  #x{{/use_freezed}}x#
  #x{{#use_meta}}#
  meta: ^1.17.0
  #x{{/use_meta}}#

dev_dependencies:
  #x{{#use_code_generation}}#
  build_runner: ^2.10.5
  #{{/use_code_generation}}x#
  #remove-start#
  coverde:
    git:
      url: https://github.com/mrverdant13/coverde.git
      ref: 019bf05daa0d9032d43a296ba67aff1cee154a8e
      path: packages/coverde_cli/
  #remove-end-x#
  #x{{#use_dart_mappable}}x#
  dart_mappable_builder: ^4.6.3
  #x{{/use_dart_mappable}}x#
  #x{{#use_freezed}}x#
  freezed: ^3.2.3
  #x{{/use_freezed}}#
  test: ^1.26.3
  very_good_analysis: ^10.0.0
