name: altoke_entity_brick_hooks
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  mason: ^0.1.0-dev.52
  path: ^1.9.0
  shell: any
  value_equality_approach: any

dev_dependencies:
  very_good_analysis: ^5.1.0

dependency_overrides:
  shell:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: b071442ea80006c2b9de19c2f69fe36ee4b102ce
      path: ./tools/shell/
  value_equality_approach:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: 1004669066d2eae47de8696387e3179f4b09061f
      path: ./tools/value_equality_approach/
