name: altoke_local_database_e2e
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dev_dependencies:
  checked_yaml: ^2.0.4
  coverde:
    git:
      url: https://github.com/mrverdant13/coverde.git
      ref: 019bf05daa0d9032d43a296ba67aff1cee154a8e
      path: packages/coverde_cli/
  local_database_alternative:
    path: ../../../tools/local_database_alternative
  mason: ^0.1.2
  meta: ^1.17.0
  mocktail: ^1.0.4
  monorepo_elements:
    path: ../../../tools/monorepo_elements
  path: ^1.9.1
  shell:
    path: ../../../tools/shell
  test: ^1.26.3
  very_good_analysis: ^10.0.0
