name: local_brick_installer
description: A tool to install bricks managed by a local monorepo.
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  monorepo_elements:
    path: ../monorepo_elements

dev_dependencies:
  very_good_analysis: ^10.0.0
