name: altoke_app_e2e
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dev_dependencies:
  checked_yaml: ^2.0.4
  coverde: ^0.3.0
  mason: ^0.1.2
  meta: ^1.17.0
  mocktail: ^1.0.4
  path: ^1.9.1
  router_package:
    path: ../../../tools/router_package
  shell:
    path: ../../../tools/shell
  state_management_package:
    path: ../../../tools/state_management_package
  test: ^1.26.3
  very_good_analysis: ^10.0.0
