name: altoke_app_e2e
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"

dev_dependencies:
  checked_yaml: ^2.0.4
  mason: ^0.1.1
  meta: ^1.17.0
  mocktail: ^1.0.4
  monorepo_elements:
    path: ../../../tools/monorepo_elements
  path: ^1.9.1
  router_package:
    path: ../../../tools/router_package
  shell:
    path: ../../../tools/shell
  test: ^1.26.2
  very_good_analysis: ^10.0.0
