name: {{objects.snakeCase()}}_storage
description: An interface for a persistent storage of {{objects.titleCase()}}.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  {{object.snakeCase()}}:
    path: ../../{{object.snakeCase()}}/

dev_dependencies:
  test: ^1.25.2
  very_good_analysis: ^5.1.0
