name: altoke_entities_e2e
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dev_dependencies:
  checked_yaml: ^2.0.4
  coverde: ^0.3.0
  mason: ^0.1.2
  meta: ^1.17.0
  mocktail: ^1.0.4
  monorepo_elements:
    path: ../../../tools/monorepo_elements
  path: ^1.9.1
  shell:
    path: ../../../tools/shell
  test: ^1.29.0
  value_equality_approach:
    path: ../../../tools/value_equality_approach
  very_good_analysis: ^10.0.0
