name: altoke_local_database_brick_hooks
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  local_database_alternative:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: 66da4935d7f254b9d02693cae5cd706575003958
      path: ./tools/local_database_alternative/
  mason: ^0.1.1
  path: ^1.9.1
  pubspec_deps_sorter:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: 66da4935d7f254b9d02693cae5cd706575003958
      path: ./tools/pubspec_deps_sorter/
  pubspec_parse: ^1.5.0
  shell:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: 66da4935d7f254b9d02693cae5cd706575003958
      path: ./tools/shell/

dev_dependencies:
  very_good_analysis: ^10.0.0
