name: altoke_reactive_caches_e2e
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dev_dependencies:
  coverde: ^0.3.0
  mason: ^0.1.2
  mocktail: ^1.0.4
  monorepo_elements:
    path: ../../../tools/monorepo_elements
  shell:
    path: ../../../tools/shell
  test: ^1.26.3
  very_good_analysis: ^10.0.0
