name: {{#requirements_met}}local_database{{/requirements_met}}
description: An interface for a persistent local database.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  common:
    path: ../../common/
  meta: ^1.17.0

dev_dependencies:
  test: ^1.29.0
  very_good_analysis: ^10.0.0
