name: brick_generator
description: A generator for bricks.
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  dart_mappable: ^4.6.1
  meta: ^1.16.0
  monorepo_elements:
    path: ../monorepo_elements
  path: ^1.9.1
  shell:
    path: ../shell

dev_dependencies:
  build_runner: ^2.7.1
  dart_mappable_builder: ^4.6.0
  test: ^1.26.2
  very_good_analysis: ^10.0.0
