name: brick_generator
description: A generator for bricks.
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  dart_mappable: ^4.6.1
  meta: ^1.17.0
  monorepo_elements:
    path: ../monorepo_elements
  path: ^1.9.1
  shell:
    path: ../shell

dev_dependencies:
  build_runner: ^2.10.4
  coverde:
    git:
      url: https://github.com/mrverdant13/coverde.git
      ref: 019bf05daa0d9032d43a296ba67aff1cee154a8e
      path: packages/coverde_cli/
  dart_mappable_builder: ^4.6.3
  test: ^1.26.3
  very_good_analysis: ^10.0.0
