name: altoke_reactive_caches
description: In-memory reactive caches.
version: 0.0.1+1
publish_to: none
#remove-start#
resolution: workspace
#remove-end#
#w 2v w#

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  altoke_common:
    #w 1v 4> w#
    #replace-start#
    path: ../../../altoke_common/reference/common/
    #with#
    # path: ../common/
    #replace-end#
  #w 1v 2> w#
  collection: ^1.19.1
  meta: ^1.17.0

dev_dependencies:
  #remove-start#
  coverde:
    git:
      url: https://github.com/mrverdant13/coverde.git
      ref: 019bf05daa0d9032d43a296ba67aff1cee154a8e
      path: packages/coverde_cli/
  #remove-end-x#
  test: ^1.26.3
  very_good_analysis: ^10.0.0
#w 1v w#
