name: altoke_entities_storage
description: An interface for a persistent storage of Altoke Entities.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  altoke_entity:
    #*w 1v 4> w*#
    #*replace-start*#
    path: ../../../altoke_entity/reference/
    #*with*#
    # path: ../../altoke_entity/
    #*replace-end*#
  #*w 1v 2> w*#

dev_dependencies:
  test: ^1.25.2
  very_good_analysis: ^5.1.0
