name: {{#requirements_met}}common{{/requirements_met}}
description: A set of {{#requirements_met}}common{{/requirements_met}} elements used across projects.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  {{#use_dart_mappable}}dart_mappable: ^4.6.1{{/use_dart_mappable}}{{#use_equatable}}equatable: ^2.0.8{{/use_equatable}}{{#use_freezed}}freezed_annotation: ^3.1.0{{/use_freezed}}{{#use_meta}}
  meta: ^1.17.0{{/use_meta}}

dev_dependencies:{{#use_code_generation}}
  build_runner: ^2.10.5
  {{/use_code_generation}}{{#use_dart_mappable}}dart_mappable_builder: ^4.6.3{{/use_dart_mappable}}{{#use_freezed}}freezed: ^3.2.3{{/use_freezed}}
  test: ^1.29.0
  very_good_analysis: ^10.0.0
