name: {{#requirements_met}}reactive_caches{{/requirements_met}}
description: In-memory reactive caches.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  common:
    path: ../common/
  collection: ^1.19.1
  meta: ^1.17.0

dev_dependencies:
  test: ^1.29.0
  very_good_analysis: ^10.0.0
