name: altoke_entities_brick_hooks
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  mason: ^0.1.1
  path: ^1.9.1
  pubspec_parse: ^1.5.0
  shell:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: 66da4935d7f254b9d02693cae5cd706575003958
      path: ./tools/shell/
  value_equality_approach:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: 66da4935d7f254b9d02693cae5cd706575003958
      path: ./tools/value_equality_approach/

dev_dependencies:
  very_good_analysis: ^10.0.0
