name: altoke_dart_package_e2e
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dev_dependencies:
  mason: ^0.1.2
  meta: ^1.17.0
  mocktail: ^1.0.4
  monorepo_elements:
    path: ../../../tools/monorepo_elements
  path: ^1.9.1
  shell:
    path: ../../../tools/shell
  test: ^1.26.3
  very_good_analysis: ^10.0.0
