name: altoke_dart_package
description: An altoke Dart package.
version: 0.0.1+1
publish_to: none
#x-remove-start#
resolution: workspace
#remove-end#

environment:
  sdk: ">=3.9.0 <4.0.0"

dev_dependencies:
  #{{#use_code_generation}}x#
  build_runner: ^2.7.1
  #{{/use_code_generation}}x#
  test: ^1.26.3
  very_good_analysis: ^10.0.0
